workflows:
  ios-release:
    name: Equi iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 20
      xcode: 15.4
    scripts:
      - name: Instalar dependencias
        script: |
          npm install --legacy-peer-deps
      - name: Prebuild nativo Expo
        script: |
          npx expo prebuild --platform ios --clean
      - name: Compilar Bundle iOS
        script: |
          cd ios
          pod install
          xcodebuild -workspace Equi.xcworkspace \
            -scheme Equi \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean build
          
          mkdir -p ../build/ios/ipa/Payload
          cp -r build/Build/Products/Release-iphoneos/Equi.app ../build/ios/ipa/Payload/
          cd ../build/ios/ipa
          zip -r Equi.ipa Payload
    artifacts:
      - build/ios/ipa/Equi.ipa