workflows:
  ios-release:
    name: Equi iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic Equi
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.equi.saludapp
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Instalar dependencias
        script: |
          npm install --legacy-peer-deps
      - name: Prebuild nativo Expo
        script: |
          npx expo prebuild --platform ios --clean
      - name: Instalar CocoaPods
        script: |
          cd ios && pod install
      - name: Configurar Firma y Certificados Apple
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.equi.saludapp" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Compilar App (.ipa)
        script: |
          cd ios
          xcodebuild -workspace Equi.xcworkspace \
            -scheme Equi \
            -configuration Release \
            -archivePath build/Equi.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/Equi.xcarchive \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath ../build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true